return {
	"folke/which-key.nvim",
	event = "VimEnter",
	opts = {
		delay = 0,
		preset = "helix",
		icons = {
			mappings = vim.g.have_nerd_font,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},
		spec = {
			-- Top-level leader mappings
			{ "<leader>", group = "[L]eader", desc = "Main leader key commands for quick access" },
			{ "<leader><space>", desc = "Smart Find Files" },
			{ "<leader>,", desc = "Buffers" },
			{ "<leader>/", desc = "Grep" },
			{ "<leader>:", desc = "Command History" },
			{ "<leader>n", desc = "Notification History" },
			{ "\\", desc = "File Explorer" },
			-- Find group
			{ "<leader>f", group = "[F]ind", desc = "Commands to find files and resources" },
			{ "<leader>fb", desc = "Buffers" },
			{ "<leader>fc", desc = "Find Config File" },
			{ "<leader>ff", desc = "Find Files" },
			{ "<leader>fg", desc = "Find Git Files" },
			{ "<leader>fp", desc = "Projects" },
			{ "<leader>fr", desc = "Recent" },
			-- Git group
			{ "<leader>g", group = "[G]it", desc = "Git-related commands and navigation" },
			{ "<leader>gb", desc = "Git Branches" },
			{ "<leader>gl", desc = "Git Log" },
			{ "<leader>gL", desc = "Git Log Line" },
			{ "<leader>gs", desc = "Git Status" },
			{ "<leader>gS", desc = "Git Stash" },
			{ "<leader>gd", desc = "Git Diff (Hunks)" },
			{ "<leader>gf", desc = "Git Log File" },
			{ "<leader>gB", desc = "Git Browse", mode = { "n", "v" } },
			{ "<leader>gg", desc = "Lazygit" },
			-- Search group
			{ "<leader>s", group = "[S]earch", desc = "Search buffers, code, and Neovim features" },
			{ "<leader>sb", desc = "Buffer Lines" },
			{ "<leader>sB", desc = "Grep Open Buffers" },
			{ "<leader>sg", desc = "Grep" },
			{ "<leader>sw", desc = "Visual selection or word", mode = { "n", "v" } },
			{ '<leader>s"', desc = "Registers" },
			{ "<leader>s/", desc = "Search History" },
			{ "<leader>sa", desc = "Autocmds" },
			{ "<leader>sc", desc = "Command History" },
			{ "<leader>sC", desc = "Commands" },
			{ "<leader>sd", desc = "Diagnostics" },
			{ "<leader>sD", desc = "Buffer Diagnostics" },
			{ "<leader>sh", desc = "Help Pages" },
			{ "<leader>sH", desc = "Highlights" },
			{ "<leader>si", desc = "Icons" },
			{ "<leader>sj", desc = "Jumps" },
			{ "<leader>sk", desc = "Keymaps" },
			{ "<leader>sl", desc = "Location List" },
			{ "<leader>sm", desc = "Marks" },
			{ "<leader>sM", desc = "Man Pages" },
			{ "<leader>sp", desc = "Search for Plugin Spec" },
			{ "<leader>sq", desc = "Quickfix List" },
			{ "<leader>sR", desc = "Resume" },
			{ "<leader>su", desc = "Undo History" },
			{ "<leader>uC", desc = "Colorschemes" },
			-- Toggle group
			{ "<leader>t", group = "[T]oggle", desc = "Toggle various Neovim settings and features" },
			{ "<leader>ts", desc = "Spelling" },
			{ "<leader>tw", desc = "Wrap" },
			{ "<leader>tL", desc = "Relative Number" },
			{ "<leader>td", desc = "Diagnostics" },
			{ "<leader>tl", desc = "Line Number" },
			{ "<leader>tc", desc = "Conceal Level" },
			{ "<leader>tT", desc = "Treesitter" },
			{ "<leader>tb", desc = "Dark Background" },
			{ "<leader>th", desc = "Inlay Hints" },
			{ "<leader>tg", desc = "Indent" },
			{ "<leader>tD", desc = "Dim" },
			-- LSP mappings
			{ "g", group = "[G]oto", desc = "LSP navigation commands" },
			{ "gd", desc = "Goto Definition" },
			{ "gD", desc = "Goto Declaration" },
			{ "gr", desc = "References" },
			{ "gI", desc = "Goto Implementation" },
			{ "gy", desc = "Goto Type Definition" },
			{ "<leader>ss", desc = "LSP Symbols" },
			{ "<leader>sS", desc = "LSP Workspace Symbols" },
			-- Other mappings
			{ "<leader>z", desc = "Toggle Zen Mode" },
			{ "<leader>Z", desc = "Toggle Zoom" },
			{ "<leader>.", desc = "Toggle Scratch Buffer" },
			{ "<leader>S", desc = "Select Scratch Buffer" },
			{ "<leader>bd", desc = "Delete Buffer" },
			{ "<leader>cR", desc = "Rename File" },
			{ "<leader>un", desc = "Dismiss All Notifications" },
			{ "<leader>N", desc = "Neovim News" },
			{ "<c-/>", desc = "Toggle Terminal" },
			{ "<c-_>", desc = "Toggle Terminal" },
			{ "]]", desc = "Next Reference", mode = { "n", "t" } },
			{ "[[", desc = "Prev Reference", mode = { "n", "t" } },
		},
	},
}
